training_set_size=opt.training_set_size
validation_set_size=opt.validation_set_size
image_set_size=opt.image_set_size
t_input_size=opt.t_input_size
v_input_size=opt.v_input_size
min_filled_image_set_size=opt.min_filled_image_set_size

training_word_query_list,
training_image_set_list,
training_index_list,
validation_word_query_list,
validation_image_set_list,
validation_index_list,
v_input_size=
   generate_toy_data(training_set_size,
		     validation_set_size,
		     t_input_size,
		     image_set_size,
		     min_filled_image_set_size
   )
